//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding_With_Area_in_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class DRIVER
    {
        public int DriverID { get; set; }
        public string DriverName { get; set; }
        public string DriverPassword { get; set; }
        public string DriverContactNo { get; set; }
        public string DriverLicenseNo { get; set; }
    }
}
