//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scaffolding_With_Area_in_Mvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int PaymentID { get; set; }
        public int UserID { get; set; }
        public decimal PaymentAmount { get; set; }
        public string PaymentCardNo { get; set; }
        public System.DateTime CardExpiryDate { get; set; }
    }
}
